### ISSUE TITLE
Support to use variable in expr

### ISSUE THREAD

**Issue by kidwm** [kidwm/node-ssi#14]
This snippet works on nginx.

```html
<!--#set var="release_date" value="2015-08-28" -->
<time datetime='<!--#echo var="date" -->'>
          <!--#if expr="$date = /(\\d+)-0?(\\d+)-0?(\\d+)/" -->
          <!--#echo var="1" --> Year
          <!--#echo var="2" --> Month
          <!--#echo var="3" --> Day
          <!--#endif -->
</time>
```

**Comment by 67726e** [comment]
Just to let you know, I'm no longer supporting this project. I'm not interested in working with Node and I no longer work at the job for which I wrote this tool.

**Comment by kidwm** [comment]
okay, I can take over, my npm id is also kidwm.

**Comment by kidwm** [comment]
now, it's my turn.

**Comment by kidwm** [comment]
Already support regular expression variable capture.
